import type { HomeImageKey } from "@/lib/site/images";

/**
 * Service scope of work — customize per service page.
 */
export const roughCarpentryScope: string[] = [
  "Framing of walls, floors, and roof systems",
  "Installation of trusses and beams",
  "Building decks and porches",
  "Installation of siding and trim per plans and specifications",
  "Installation of vapor barrier at siding locations",
  "Installation of all structural shear panels — full wrap when required",
  "Installation of all structural hardware and strapping",
  "Building interior wood stairs",
  "Forklift and operator services as needed",
  "Obtaining lumber certifications when required",
  "Cleanup of material generated by our operations",
];

export type ServiceDetail = {
  slug: string;
  name: string;
  /** Page H1 with primary keyword + geo. */
  h1: string;
  metaTitle: string;
  metaDescription: string;
  heroImage: HomeImageKey;
  intro: string[];
  /** Section heading for the scope list. */
  scopeHeading: string;
  scope: string[];
  /** Two audience-specific blurbs for the dual-audience angle. */
  residential: { heading: string; body: string };
  commercial: { heading: string; body: string };
  faqs: { question: string; answer: string }[];
};

export const serviceDetails: Record<string, ServiceDetail> = {
  framing: {
    slug: "framing",
    name: "Rough Framing",
    h1: "Rough Framing Contractor — Bay Area & Northern California",
    metaTitle: "Rough Framing Contractor Bay Area CA",
    metaDescription:
      "Residential and commercial rough carpentry and framing across the Bay Area, Central Valley, and Southern California — walls, floors, roofs, trusses, shear panels, and structural hardware. License #000000.",
    heroImage: "residentialRoofFraming",
    intro: [
      "Framing is the backbone of every build — and it is our specialty, not a side service. Legson Media delivers precise, code-compliant rough carpentry for walls, floors, and roof systems across the Bay Area, Central Valley, and Southern California.",
      "From a single custom home to a multi-plan production community, our experienced crews frame square, plumb, and to spec so every structure passes inspection the first time.",
    ],
    scopeHeading: "Our Rough Carpentry Scope",
    scope: roughCarpentryScope,
    residential: {
      heading: "Residential Framing",
      body: "Custom homes, additions, and remodels framed with the precision and structural know-how that protects everything built on top of the frame.",
    },
    commercial: {
      heading: "Commercial & Production-Builder Framing",
      body: "We are a trusted rough-carpentry subcontractor for production builders and general contractors, delivering multi-plan tract communities, condominiums, and multi-family projects on schedule.",
    },
    faqs: [
      {
        question: "Do you frame for production builders and general contractors?",
        answer:
          "Yes. We work with production builders and general contractors — handling full project packages from single sites to multi-plan communities.",
      },
      {
        question: "What does your framing scope include?",
        answer:
          "Our rough carpentry scope covers framing of walls, floors, and roofs; trusses and beams; decks and porches; siding and trim; vapor barrier at siding; structural shear panels; structural hardware and strapping; interior wood stairs; forklift services; lumber certifications; and material cleanup.",
      },
    ],
  },
  siding: {
    slug: "siding",
    name: "Siding",
    h1: "Siding Installation — Bay Area & Northern California",
    metaTitle: "Siding Installation Bay Area CA",
    metaDescription:
      "Siding and trim installation, replacement, and weather protection across the Bay Area and Northern California — installed by framing-first specialists. License #000000.",
    heroImage: "sidingInstallation",
    intro: [
      "We install and replace siding and trim per plans and specifications, enhancing both the durability and appearance of your building while protecting it against the elements.",
      "Because we are framing-first specialists, our siding work is built on a structurally sound envelope — including vapor barrier at siding locations and full wrap where required.",
    ],
    scopeHeading: "What Our Siding Work Covers",
    scope: [
      "Siding and trim installation per plans and specifications",
      "Siding replacement and weatherproofing upgrades",
      "Vapor barrier installation at siding locations",
      "Full structural wrap when required by the scope of work",
      "Coordination with framing and shear-panel work for a tight building envelope",
    ],
    residential: {
      heading: "Residential Siding",
      body: "Protect your home and boost curb appeal with siding and trim installed to last through California seasons.",
    },
    commercial: {
      heading: "Production & Multi-Family Siding",
      body: "Siding packages for production communities and multi-family builds, coordinated with our framing scope to keep your schedule moving.",
    },
    faqs: [
      {
        question: "Do you install vapor barrier with siding?",
        answer:
          "Yes — we install vapor barrier at siding locations and provide full structural wrap when the scope of work requires it.",
      },
    ],
  },
  decks: {
    slug: "decks",
    name: "Decks & Porches",
    h1: "Deck & Porch Construction — Bay Area & Northern California",
    metaTitle: "Deck Construction Bay Area CA",
    metaDescription:
      "Custom deck and porch construction across the Bay Area and Northern California, built by structural framing specialists. License #000000.",
    heroImage: "deckPorch",
    intro: [
      "Decks and porches are part of our core rough-carpentry scope. We build outdoor living structures that are square, solid, and built to last through California seasons.",
      "Every deck and porch is framed with the same structural precision we bring to walls, floors, and roofs.",
    ],
    scopeHeading: "What We Build",
    scope: [
      "New deck and porch framing and construction",
      "Structural posts, beams, and joist systems",
      "Integration with home framing and exterior siding",
      "Structural hardware and strapping for code compliance",
    ],
    residential: {
      heading: "Residential Decks & Porches",
      body: "Custom wood and composite outdoor living spaces designed and built to match your home.",
    },
    commercial: {
      heading: "Production & Multi-Family",
      body: "Deck and porch packages for production homes and multi-family communities, delivered alongside the framing scope.",
    },
    faqs: [
      {
        question: "Are decks part of your framing scope?",
        answer:
          "Yes. Building decks and porches is included in our standard rough-carpentry scope of work.",
      },
    ],
  },
  remodeling: {
    slug: "remodeling",
    name: "Remodeling",
    h1: "Remodeling Contractor — Bay Area & Northern California",
    metaTitle: "Remodeling Contractor Bay Area CA",
    metaDescription:
      "Remodeling across the Bay Area and Northern California — structural modifications, renovations, additions, and upgrades for residential and commercial spaces. License #000000.",
    heroImage: "customKitchenRemodel",
    intro: [
      "Beyond framing, Legson Media provides remodeling services including structural modifications, renovations, additions, and upgrades to existing spaces.",
      "We work closely with clients to complete projects efficiently, safely, and according to design specifications — committed to quality assurance, reliability, and on-time delivery.",
    ],
    scopeHeading: "What Our Remodeling Covers",
    scope: [
      "Structural modifications to existing homes and buildings",
      "Renovations and full-room remodels",
      "Additions and expansions",
      "Upgrades to existing residential and commercial spaces",
      "Code-compliant structural work with required certifications",
      "Coordination with architects, engineers, and general contractors",
    ],
    residential: {
      heading: "Homeowners",
      body: "Remodels, additions, and upgrades managed with clear communication from estimate to final walkthrough.",
    },
    commercial: {
      heading: "Builders & General Contractors",
      body: "Dependable subcontracting capacity and resources to support renovations and structural modifications across Northern California.",
    },
    faqs: [
      {
        question: "What types of remodeling projects do you take on?",
        answer:
          "Legson Media handles structural modifications, renovations, additions, and upgrades for both residential and commercial projects — working with homeowners, production builders, and general contractors.",
      },
    ],
  },
};

export const serviceOrder = [
  "framing",
  "remodeling",
  "siding",
  "decks",
] as const;
